### ISSUE TITLE
Enable more complex retention policies

### ISSUE THREAD

**Issue by MrMarlin** [tomochain/goutte#16]
It would be nice, to be able to set multiple retention "scope" like, keep:
- One Snapshot for the last seven days (each day)
- one Snapshot for the last four weeks (one Snapshot of each week)
- one Snapshot for the last twelve months (one snapshot of each month)

**Comment by etienne-napoleone** [comment]
That could be nice to add indeed!
As a workaround for now it is possible to achieve this by having multiple config files and running the goutte once per config.

**Comment by MrMarlin** [comment]
This was my first idea. But wouldn't my weekly config with retention=4 prune some of my weekly snapshots with retention=7, since there is no differentiation in the prefixes?

**Comment by etienne-napoleone** [comment]
Ah yes you're right, sorry it's been a while!
I will see to refactor goutte to accept something like:
```toml
[droplets]
default_retention = 5

  [[droplets.by_name]]
  name = "server01"
  retention = 3

  [[droplets.by_name]]
  name = "server02"

  [[droplets.by_tag]]
  tag = "prod"
  retention = 20

[volumes]

  [[volumes.by_name]]
  # ...
```
